# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/qxmap/edge.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from risenlighten.lasvsim.api.geometry import geometry_pb2 as api_dot_v1_dot_geometry_dot_geometry__pb2
from risenlighten.lasvsim.api.qxmap import link_pb2 as api_dot_v1_dot_qxmap_dot_link__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pi/v1/qxmap/edge.proto\x12)risenlighten.lasvsim.api.datahub.qxmap.v1\x1a\x1e\x61pi/v1/geometry/geometry.proto\x1a\x17\x61pi/v1/qxmap/link.proto\"\xcb\x02\n\x07Segment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06map_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x19\n\x11start_junction_id\x18\n \x01(\t\x12\x17\n\x0f\x65nd_junction_id\x18\x0b \x01(\t\x12\x18\n\x10pair_segment_ids\x18\x0c \x03(\t\x12\x10\n\x08s_offset\x18\r \x01(\x01\x12\x0f\n\x07road_id\x18\x0e \x01(\t\x12\x0e\n\x06length\x18\x0f \x01(\x01\x12\x46\n\rordered_links\x18\x64 \x03(\x0b\x32/.risenlighten.lasvsim.api.datahub.qxmap.v1.Link\x12M\n\rtraffic_signs\x18\x65 \x03(\x0b\x32\x36.risenlighten.lasvsim.api.datahub.qxmap.v1.TrafficSign\"n\n\x06Object\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12J\n\x05shape\x18\x03 \x03(\x0b\x32;.risenlighten.lasvsim.api.datahub.geometry.v1.DirectedPoint\"\xbf\x02\n\x0bTrafficSign\x12\n\n\x02id\x18\x01 \x01(\t\x12T\n\x04type\x18\x02 \x01(\x0e\x32\x46.risenlighten.lasvsim.api.datahub.qxmap.v1.TrafficSign.TrafficSignType\x12M\n\x08position\x18\x03 \x01(\x0b\x32;.risenlighten.lasvsim.api.datahub.geometry.v1.DirectedPoint\"\x7f\n\x0fTrafficSignType\x12\x15\n\x11SIGN_TYPE_UNKNOWN\x10\x00\x12\x19\n\x15SIGN_TYPE_SPEED_LIMIT\x10\x01\x12\x18\n\x14SIGN_TYPE_GUIDE_SIGN\x10\x02\x12 \n\x1cSIGN_TYPE_TRAFFIC_LIGHT_POLE\x10\x03\x42;Z9git.risenlighten.com/lasvsim/datahub/api/qxmap/v1;qxmapv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.qxmap.edge_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z9git.risenlighten.com/lasvsim/datahub/api/qxmap/v1;qxmapv1'
  _SEGMENT._serialized_start=128
  _SEGMENT._serialized_end=459
  _OBJECT._serialized_start=461
  _OBJECT._serialized_end=571
  _TRAFFICSIGN._serialized_start=574
  _TRAFFICSIGN._serialized_end=893
  _TRAFFICSIGN_TRAFFICSIGNTYPE._serialized_start=766
  _TRAFFICSIGN_TRAFFICSIGNTYPE._serialized_end=893
# @@protoc_insertion_point(module_scope)
