# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/qxmap/link.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from risenlighten.lasvsim.api.geometry import geometry_pb2 as api_dot_v1_dot_geometry_dot_geometry__pb2
from risenlighten.lasvsim.api.qxmap import lane_pb2 as api_dot_v1_dot_qxmap_dot_lane__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pi/v1/qxmap/link.proto\x12)risenlighten.lasvsim.api.datahub.qxmap.v1\x1a\x1e\x61pi/v1/geometry/geometry.proto\x1a\x17\x61pi/v1/qxmap/lane.proto\"\xf9\x06\n\x04Link\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06map_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x46\n\x04type\x18\x04 \x01(\x0e\x32\x38.risenlighten.lasvsim.api.datahub.qxmap.v1.Link.LinkType\x12\x10\n\x08pair_ids\x18\x05 \x03(\t\x12@\n\x06widths\x18\x06 \x03(\x0b\x32\x30.risenlighten.lasvsim.api.datahub.qxmap.v1.Width\x12\x46\n\rordered_lanes\x18\x07 \x03(\x0b\x32/.risenlighten.lasvsim.api.datahub.qxmap.v1.Lane\x12\x0e\n\x06length\x18\x08 \x01(\x01\x12\x10\n\x08s_offset\x18\t \x01(\x01\x12\x10\n\x08link_num\x18\n \x01(\x05\x12\x11\n\tparent_id\x18\x0b \x01(\t\x12T\n\x0ereference_line\x18\x62 \x03(\x0b\x32<.risenlighten.lasvsim.api.datahub.geometry.v1.ReferencePoint\x12\x19\n\x11upstream_link_ids\x18\x63 \x03(\t\x12\x1b\n\x13\x64ownstream_link_ids\x18\x64 \x03(\t\x12T\n\rleft_boundary\x18\x65 \x01(\x0b\x32\x38.risenlighten.lasvsim.api.datahub.geometry.v1.LineStringH\x00\x88\x01\x01\x12U\n\x0eright_boundary\x18\x66 \x01(\x0b\x32\x38.risenlighten.lasvsim.api.datahub.geometry.v1.LineStringH\x01\x88\x01\x01\"\xbb\x01\n\x08LinkType\x12\x15\n\x11LINK_TYPE_UNKNOWN\x10\x00\x12\x17\n\x13LINK_TYPE_WAIT_AREA\x10\x01\x12\x18\n\x14LINK_TYPE_ROUNDABOUT\x10\x02\x12\x15\n\x11LINK_TYPE_SEGMENT\x10\x03\x12\x16\n\x12LINK_TYPE_JUNCTION\x10\x04\x12\x1c\n\x18LINK_TYPE_PRE_TURN_RIGHT\x10\x05\x12\x18\n\x14LINK_TYPE_PRE_U_TURN\x10\x06\x42\x10\n\x0e_left_boundaryB\x11\n\x0f_right_boundaryB;Z9git.risenlighten.com/lasvsim/datahub/api/qxmap/v1;qxmapv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.qxmap.link_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z9git.risenlighten.com/lasvsim/datahub/api/qxmap/v1;qxmapv1'
  _LINK._serialized_start=128
  _LINK._serialized_end=1017
  _LINK_LINKTYPE._serialized_start=793
  _LINK_LINKTYPE._serialized_end=980
# @@protoc_insertion_point(module_scope)
