# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/qxmap/qxmap.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from risenlighten.lasvsim.api.qxmap import node_pb2 as api_dot_v1_dot_qxmap_dot_node__pb2
from risenlighten.lasvsim.api.qxmap import edge_pb2 as api_dot_v1_dot_qxmap_dot_edge__pb2
from risenlighten.lasvsim.api.qxmap import road_pb2 as api_dot_v1_dot_qxmap_dot_road__pb2
from risenlighten.lasvsim.api.geometry import geometry_pb2 as api_dot_v1_dot_geometry_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61pi/v1/qxmap/qxmap.proto\x12)risenlighten.lasvsim.api.datahub.qxmap.v1\x1a\x17\x61pi/v1/qxmap/node.proto\x1a\x17\x61pi/v1/qxmap/edge.proto\x1a\x17\x61pi/v1/qxmap/road.proto\x1a\x1e\x61pi/v1/geometry/geometry.proto\"\xf8\x02\n\x05Qxmap\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\t\x12\x41\n\x06header\x18\t \x01(\x0b\x32\x31.risenlighten.lasvsim.api.datahub.qxmap.v1.Header\x12\x46\n\tjunctions\x18\n \x03(\x0b\x32\x33.risenlighten.lasvsim.api.datahub.qxmap.v1.Junction\x12\x44\n\x08segments\x18\x0b \x03(\x0b\x32\x32.risenlighten.lasvsim.api.datahub.qxmap.v1.Segment\x12>\n\x05roads\x18\x0c \x03(\x0b\x32/.risenlighten.lasvsim.api.datahub.qxmap.v1.Road\x12\x42\n\x07mappers\x18\r \x03(\x0b\x32\x31.risenlighten.lasvsim.api.datahub.qxmap.v1.Mapper\"\xe0\x01\n\x06Mapper\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06map_id\x18\x02 \x01(\t\x12\x19\n\x0corigin_xpath\x18\n \x01(\tH\x00\x88\x01\x01\x12\x16\n\x0eorigin_elem_id\x18\x0b \x01(\t\x12\x18\n\x10origin_elem_type\x18\x0c \x01(\t\x12\x19\n\x0ctarget_xpath\x18\x14 \x01(\tH\x01\x88\x01\x01\x12\x16\n\x0etarget_elem_id\x18\x15 \x01(\t\x12\x18\n\x10target_elem_type\x18\x16 \x01(\tB\x0f\n\r_origin_xpathB\x0f\n\r_target_xpath\"\xbe\x01\n\x06Header\x12\r\n\x05north\x18\x01 \x01(\x01\x12\r\n\x05south\x18\x02 \x01(\x01\x12\x0c\n\x04\x65\x61st\x18\x03 \x01(\x01\x12\x0c\n\x04west\x18\x04 \x01(\x01\x12I\n\x0c\x63\x65nter_point\x18\x05 \x01(\x0b\x32\x33.risenlighten.lasvsim.api.datahub.geometry.v1.Point\x12\x0f\n\x07version\x18\x06 \x01(\t\x12\x0c\n\x04zone\x18\x07 \x01(\x01\x12\x10\n\x08use_bias\x18\x08 \x01(\x08\x42;Z9git.risenlighten.com/lasvsim/datahub/api/qxmap/v1;qxmapv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.qxmap.qxmap_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z9git.risenlighten.com/lasvsim/datahub/api/qxmap/v1;qxmapv1'
  _QXMAP._serialized_start=179
  _QXMAP._serialized_end=555
  _MAPPER._serialized_start=558
  _MAPPER._serialized_end=782
  _HEADER._serialized_start=785
  _HEADER._serialized_end=975
# @@protoc_insertion_point(module_scope)
