# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api/v1/qxmap/road.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from risenlighten.lasvsim.api.geometry import geometry_pb2 as api_dot_v1_dot_geometry_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pi/v1/qxmap/road.proto\x12)risenlighten.lasvsim.api.datahub.qxmap.v1\x1a\x1e\x61pi/v1/geometry/geometry.proto\"\xd4\x04\n\x04Road\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06map_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x46\n\x04type\x18\x04 \x01(\x0e\x32\x38.risenlighten.lasvsim.api.datahub.qxmap.v1.Road.RoadType\x12\x0e\n\x06length\x18\x05 \x01(\x01\x12J\n\tneighbors\x18\t \x03(\x0b\x32\x37.risenlighten.lasvsim.api.datahub.qxmap.v1.RoadPosition\x12R\n\x0e\x63ontrol_points\x18\n \x03(\x0b\x32:.risenlighten.lasvsim.api.datahub.geometry.v1.ControlPoint\x12T\n\x0ereference_line\x18\x0b \x03(\x0b\x32<.risenlighten.lasvsim.api.datahub.geometry.v1.ReferencePoint\x12\x44\n\x08sections\x18\r \x03(\x0b\x32\x32.risenlighten.lasvsim.api.datahub.qxmap.v1.Section\x12W\n\x12junction_positions\x18\x0e \x03(\x0b\x32;.risenlighten.lasvsim.api.datahub.qxmap.v1.JunctionPosition\"5\n\x08RoadType\x12\x15\n\x11ROAD_TYPE_UNKNOWN\x10\x00\x12\x12\n\x0eROAD_TYPE_RAMP\x10\x01\":\n\x0cRoadPosition\x12\x0f\n\x07road_id\x18\x01 \x01(\t\x12\x0e\n\x06road_s\x18\x02 \x01(\x01\x12\t\n\x01s\x18\x03 \x01(\x01\"N\n\x10JunctionPosition\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bjunction_id\x18\x02 \x01(\t\x12\t\n\x01s\x18\x03 \x01(\x01\x12\x0e\n\x06length\x18\x05 \x01(\x01\"\x97\x01\n\x07Section\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01s\x18\x02 \x01(\x01\x12\x0e\n\x06length\x18\x04 \x01(\x01\x12\x19\n\x11start_junction_id\x18\n \x01(\t\x12\x17\n\x0f\x65nd_junction_id\x18\x0b \x01(\t\x12\x17\n\x0fleft_segment_id\x18\x0c \x01(\t\x12\x18\n\x10right_segment_id\x18\r \x01(\tB;Z9git.risenlighten.com/lasvsim/datahub/api/qxmap/v1;qxmapv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.v1.qxmap.road_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z9git.risenlighten.com/lasvsim/datahub/api/qxmap/v1;qxmapv1'
  _ROAD._serialized_start=103
  _ROAD._serialized_end=699
  _ROAD_ROADTYPE._serialized_start=646
  _ROAD_ROADTYPE._serialized_end=699
  _ROADPOSITION._serialized_start=701
  _ROADPOSITION._serialized_end=759
  _JUNCTIONPOSITION._serialized_start=761
  _JUNCTIONPOSITION._serialized_end=839
  _SECTION._serialized_start=842
  _SECTION._serialized_end=993
# @@protoc_insertion_point(module_scope)
