# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from risenlighten.lasvsim.train_sim.api.trainsim import trainsim_pb2 as risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2


class SimulationStub(object):
    """--------- 仿真器部分 ---------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/Init',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.InitReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.InitRes.FromString,
                )
        self.Step = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/Step',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StepReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StepRes.FromString,
                )
        self.Stop = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/Stop',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StopReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StopRes.FromString,
                )
        self.Reset = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/Reset',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.ResetReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.ResetRes.FromString,
                )
        self.GetTrafficMap = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetTrafficMap',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTrafficMapReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTrafficMapRes.FromString,
                )
        self.GetVehicleIdList = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleIdList',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleIdListReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleIdListRes.FromString,
                )
        self.GetTestVehicleIdList = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetTestVehicleIdList',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTestVehicleIdListReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTestVehicleIdListRes.FromString,
                )
        self.GetVehicleBaseInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleBaseInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleBaseInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleBaseInfoRes.FromString,
                )
        self.GetVehiclePosition = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehiclePosition',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePositionReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePositionRes.FromString,
                )
        self.GetVehicleMovingInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleMovingInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleMovingInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleMovingInfoRes.FromString,
                )
        self.GetVehicleControlInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleControlInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleControlInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleControlInfoRes.FromString,
                )
        self.GetVehiclePerceptionInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehiclePerceptionInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePerceptionInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePerceptionInfoRes.FromString,
                )
        self.GetVehicleReferenceLines = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleReferenceLines',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleReferenceLinesReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleReferenceLinesRes.FromString,
                )
        self.GetVehiclePlanningInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehiclePlanningInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePlanningInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePlanningInfoRes.FromString,
                )
        self.GetVehicleNavigationInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleNavigationInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleNavigationInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleNavigationInfoRes.FromString,
                )
        self.GetVehicleTrackPathInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleTrackPathInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTrackPathInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTrackPathInfoRes.FromString,
                )
        self.SetVehiclePlanningInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehiclePlanningInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePlanningInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePlanningInfoRes.FromString,
                )
        self.GetVehicleDynamicParamsInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleDynamicParamsInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleDynamicParamInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleDynamicParamInfoRes.FromString,
                )
        self.GetVehicleCollisionInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleCollisionInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleCollisionInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleCollisionInfoRes.FromString,
                )
        self.GetVehicleTargetSpeed = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleTargetSpeed',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTargetSpeedReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTargetSpeedRes.FromString,
                )
        self.SetVehicleControlInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehicleControlInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleControlInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleControlInfoRes.FromString,
                )
        self.SetVehiclePosition = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehiclePosition',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePositionReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePositionRes.FromString,
                )
        self.SetVehicleMovingInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehicleMovingInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleMovingInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleMovingInfoRes.FromString,
                )
        self.SetVehicleBaseInfo = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehicleBaseInfo',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleBaseInfoReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleBaseInfoRes.FromString,
                )
        self.SetVehicleDestination = channel.unary_unary(
                '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehicleDestination',
                request_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleDestinationReq.SerializeToString,
                response_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleDestinationRes.FromString,
                )


class SimulationServicer(object):
    """--------- 仿真器部分 ---------
    """

    def Init(self, request, context):
        """初始化新仿真器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """执行仿真
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """停止仿真器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """重置仿真器
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrafficMap(self, request, context):
        """--------- 地图部分 ---------
        训练平台初版本暂时不需要
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleIdList(self, request, context):
        """--------- 车辆部分 ---------

        根据仿真ID获取所有车辆ID列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestVehicleIdList(self, request, context):
        """根据仿真ID获取测试车辆ID列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleBaseInfo(self, request, context):
        """根据车辆ID列表获取车辆基本信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehiclePosition(self, request, context):
        """根据车辆ID列表获取车辆位置信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleMovingInfo(self, request, context):
        """根据车辆ID列表获取车辆运动信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleControlInfo(self, request, context):
        """根据车辆ID列表获取车辆控制参数信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehiclePerceptionInfo(self, request, context):
        """根据车辆ID获取车辆感知信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleReferenceLines(self, request, context):
        """获取车辆可选参考线
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehiclePlanningInfo(self, request, context):
        """获取车辆规划路径
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleNavigationInfo(self, request, context):
        """获取车辆导航信息,暂不支持route_nav以及lane_nav
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleTrackPathInfo(self, request, context):
        """获取车辆局部规划轨迹信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehiclePlanningInfo(self, request, context):
        """修改车辆规划路径
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleDynamicParamsInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleCollisionInfo(self, request, context):
        """获取车辆碰撞信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVehicleTargetSpeed(self, request, context):
        """获取车辆目标速度
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleControlInfo(self, request, context):
        """修改车辆控制参数(方向盘转角、纵向加速度)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehiclePosition(self, request, context):
        """修改车辆点位信息{x,y,z}, phi
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleMovingInfo(self, request, context):
        """修改车辆运动信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleBaseInfo(self, request, context):
        """修改车辆基础信息, 暂不支持动力学相关参数
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVehicleDestination(self, request, context):
        """修改车辆终点
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.InitReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.InitRes.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StepReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StepRes.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StopReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StopRes.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.ResetReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.ResetRes.SerializeToString,
            ),
            'GetTrafficMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrafficMap,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTrafficMapReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTrafficMapRes.SerializeToString,
            ),
            'GetVehicleIdList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleIdList,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleIdListReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleIdListRes.SerializeToString,
            ),
            'GetTestVehicleIdList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestVehicleIdList,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTestVehicleIdListReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTestVehicleIdListRes.SerializeToString,
            ),
            'GetVehicleBaseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleBaseInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleBaseInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleBaseInfoRes.SerializeToString,
            ),
            'GetVehiclePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehiclePosition,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePositionReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePositionRes.SerializeToString,
            ),
            'GetVehicleMovingInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleMovingInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleMovingInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleMovingInfoRes.SerializeToString,
            ),
            'GetVehicleControlInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleControlInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleControlInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleControlInfoRes.SerializeToString,
            ),
            'GetVehiclePerceptionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehiclePerceptionInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePerceptionInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePerceptionInfoRes.SerializeToString,
            ),
            'GetVehicleReferenceLines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleReferenceLines,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleReferenceLinesReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleReferenceLinesRes.SerializeToString,
            ),
            'GetVehiclePlanningInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehiclePlanningInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePlanningInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePlanningInfoRes.SerializeToString,
            ),
            'GetVehicleNavigationInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleNavigationInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleNavigationInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleNavigationInfoRes.SerializeToString,
            ),
            'GetVehicleTrackPathInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleTrackPathInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTrackPathInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTrackPathInfoRes.SerializeToString,
            ),
            'SetVehiclePlanningInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehiclePlanningInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePlanningInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePlanningInfoRes.SerializeToString,
            ),
            'GetVehicleDynamicParamsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleDynamicParamsInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleDynamicParamInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleDynamicParamInfoRes.SerializeToString,
            ),
            'GetVehicleCollisionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleCollisionInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleCollisionInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleCollisionInfoRes.SerializeToString,
            ),
            'GetVehicleTargetSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVehicleTargetSpeed,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTargetSpeedReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTargetSpeedRes.SerializeToString,
            ),
            'SetVehicleControlInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleControlInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleControlInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleControlInfoRes.SerializeToString,
            ),
            'SetVehiclePosition': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehiclePosition,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePositionReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePositionRes.SerializeToString,
            ),
            'SetVehicleMovingInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleMovingInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleMovingInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleMovingInfoRes.SerializeToString,
            ),
            'SetVehicleBaseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleBaseInfo,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleBaseInfoReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleBaseInfoRes.SerializeToString,
            ),
            'SetVehicleDestination': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVehicleDestination,
                    request_deserializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleDestinationReq.FromString,
                    response_serializer=risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleDestinationRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'risenlighten.lasvsim.train_sim.api.trainsim.Simulation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulation(object):
    """--------- 仿真器部分 ---------
    """

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/Init',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.InitReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.InitRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/Step',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StepReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StepRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/Stop',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StopReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.StopRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/Reset',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.ResetReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.ResetRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTrafficMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetTrafficMap',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTrafficMapReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTrafficMapRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleIdList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleIdList',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleIdListReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleIdListRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTestVehicleIdList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetTestVehicleIdList',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTestVehicleIdListReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetTestVehicleIdListRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleBaseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleBaseInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleBaseInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleBaseInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehiclePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehiclePosition',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePositionReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePositionRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleMovingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleMovingInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleMovingInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleMovingInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleControlInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleControlInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleControlInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleControlInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehiclePerceptionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehiclePerceptionInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePerceptionInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePerceptionInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleReferenceLines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleReferenceLines',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleReferenceLinesReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleReferenceLinesRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehiclePlanningInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehiclePlanningInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePlanningInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehiclePlanningInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleNavigationInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleNavigationInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleNavigationInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleNavigationInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleTrackPathInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleTrackPathInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTrackPathInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTrackPathInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehiclePlanningInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehiclePlanningInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePlanningInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePlanningInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleDynamicParamsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleDynamicParamsInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleDynamicParamInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleDynamicParamInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleCollisionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleCollisionInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleCollisionInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleCollisionInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVehicleTargetSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/GetVehicleTargetSpeed',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTargetSpeedReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.GetVehicleTargetSpeedRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleControlInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehicleControlInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleControlInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleControlInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehiclePosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehiclePosition',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePositionReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehiclePositionRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleMovingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehicleMovingInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleMovingInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleMovingInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleBaseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehicleBaseInfo',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleBaseInfoReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleBaseInfoRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetVehicleDestination(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/risenlighten.lasvsim.train_sim.api.trainsim.Simulation/SetVehicleDestination',
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleDestinationReq.SerializeToString,
            risenlighten_dot_lasvsim_dot_train__sim_dot_api_dot_trainsim_dot_trainsim__pb2.SetVehicleDestinationRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
